version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5050:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spc
#    volumes:
#      - type: tmpfs
#        target: /dev/shm
#        tmpfs:
#          size: 134217728 # 128*2^20 bytes = 128Mb